/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type StockUpdateResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: components.ErrorT | undefined;
};

export type StockUpdateRequestBody = {
    drink?: components.DrinkInput | undefined;
    ingredient?: components.IngredientInput | undefined;
};

/** @internal */
export namespace StockUpdateResponse$ {
    export const inboundSchema: z.ZodType<StockUpdateResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Error: components.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Error?: components.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            error: components.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                error: "Error",
            });
        });
}

/** @internal */
export namespace StockUpdateRequestBody$ {
    export const inboundSchema: z.ZodType<StockUpdateRequestBody, z.ZodTypeDef, unknown> = z.object(
        {
            drink: components.DrinkInput$.inboundSchema.optional(),
            ingredient: components.IngredientInput$.inboundSchema.optional(),
        }
    );

    export type Outbound = {
        drink?: components.DrinkInput$.Outbound | undefined;
        ingredient?: components.IngredientInput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateRequestBody> =
        z.object({
            drink: components.DrinkInput$.outboundSchema.optional(),
            ingredient: components.IngredientInput$.outboundSchema.optional(),
        });
}
