/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type StockUpdateResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * An unknown error occurred interacting with the API.
     */
    error?: components.ErrorT | undefined;
};

export type StockUpdateRequestBody = {
    drink?: components.DrinkInput | undefined;
    ingredient?: components.IngredientInput | undefined;
};

/** @internal */
export namespace StockUpdateResponse$ {
    export const inboundSchema: z.ZodType<StockUpdateResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Error: components.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Error === undefined ? null : { error: v.Error }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Error?: components.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            error: components.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.error === undefined ? null : { Error: v.error }),
            };
        });
}

/** @internal */
export namespace StockUpdateRequestBody$ {
    export const inboundSchema: z.ZodType<StockUpdateRequestBody, z.ZodTypeDef, unknown> = z
        .object({
            drink: components.DrinkInput$.inboundSchema.optional(),
            ingredient: components.IngredientInput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.drink === undefined ? null : { drink: v.drink }),
                ...(v.ingredient === undefined ? null : { ingredient: v.ingredient }),
            };
        });

    export type Outbound = {
        drink?: components.DrinkInput$.Outbound | undefined;
        ingredient?: components.IngredientInput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, StockUpdateRequestBody> = z
        .object({
            drink: components.DrinkInput$.outboundSchema.optional(),
            ingredient: components.IngredientInput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.drink === undefined ? null : { drink: v.drink }),
                ...(v.ingredient === undefined ? null : { ingredient: v.ingredient }),
            };
        });
}
