/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StockUpdateRequestBody = {
  drink?: components.DrinkInput | undefined;
  ingredient?: components.IngredientInput | undefined;
};

export type StockUpdateResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const StockUpdateRequestBody$inboundSchema: z.ZodType<
  StockUpdateRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  drink: components.DrinkInput$inboundSchema.optional(),
  ingredient: components.IngredientInput$inboundSchema.optional(),
});

/** @internal */
export type StockUpdateRequestBody$Outbound = {
  drink?: components.DrinkInput$Outbound | undefined;
  ingredient?: components.IngredientInput$Outbound | undefined;
};

/** @internal */
export const StockUpdateRequestBody$outboundSchema: z.ZodType<
  StockUpdateRequestBody$Outbound,
  z.ZodTypeDef,
  StockUpdateRequestBody
> = z.object({
  drink: components.DrinkInput$outboundSchema.optional(),
  ingredient: components.IngredientInput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StockUpdateRequestBody$ {
  /** @deprecated use `StockUpdateRequestBody$inboundSchema` instead. */
  export const inboundSchema = StockUpdateRequestBody$inboundSchema;
  /** @deprecated use `StockUpdateRequestBody$outboundSchema` instead. */
  export const outboundSchema = StockUpdateRequestBody$outboundSchema;
  /** @deprecated use `StockUpdateRequestBody$Outbound` instead. */
  export type Outbound = StockUpdateRequestBody$Outbound;
}

export function stockUpdateRequestBodyToJSON(
  stockUpdateRequestBody: StockUpdateRequestBody,
): string {
  return JSON.stringify(
    StockUpdateRequestBody$outboundSchema.parse(stockUpdateRequestBody),
  );
}

export function stockUpdateRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<StockUpdateRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StockUpdateRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StockUpdateRequestBody' from JSON`,
  );
}

/** @internal */
export const StockUpdateResponse$inboundSchema: z.ZodType<
  StockUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Error": "error",
  });
});

/** @internal */
export type StockUpdateResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const StockUpdateResponse$outboundSchema: z.ZodType<
  StockUpdateResponse$Outbound,
  z.ZodTypeDef,
  StockUpdateResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StockUpdateResponse$ {
  /** @deprecated use `StockUpdateResponse$inboundSchema` instead. */
  export const inboundSchema = StockUpdateResponse$inboundSchema;
  /** @deprecated use `StockUpdateResponse$outboundSchema` instead. */
  export const outboundSchema = StockUpdateResponse$outboundSchema;
  /** @deprecated use `StockUpdateResponse$Outbound` instead. */
  export type Outbound = StockUpdateResponse$Outbound;
}

export function stockUpdateResponseToJSON(
  stockUpdateResponse: StockUpdateResponse,
): string {
  return JSON.stringify(
    StockUpdateResponse$outboundSchema.parse(stockUpdateResponse),
  );
}

export function stockUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<StockUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StockUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StockUpdateResponse' from JSON`,
  );
}
