/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateOrderOrderUpdateResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const CreateOrderOrderUpdateResponse$inboundSchema: z.ZodType<
  CreateOrderOrderUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Error": "error",
  });
});

/** @internal */
export type CreateOrderOrderUpdateResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const CreateOrderOrderUpdateResponse$outboundSchema: z.ZodType<
  CreateOrderOrderUpdateResponse$Outbound,
  z.ZodTypeDef,
  CreateOrderOrderUpdateResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrderOrderUpdateResponse$ {
  /** @deprecated use `CreateOrderOrderUpdateResponse$inboundSchema` instead. */
  export const inboundSchema = CreateOrderOrderUpdateResponse$inboundSchema;
  /** @deprecated use `CreateOrderOrderUpdateResponse$outboundSchema` instead. */
  export const outboundSchema = CreateOrderOrderUpdateResponse$outboundSchema;
  /** @deprecated use `CreateOrderOrderUpdateResponse$Outbound` instead. */
  export type Outbound = CreateOrderOrderUpdateResponse$Outbound;
}

export function createOrderOrderUpdateResponseToJSON(
  createOrderOrderUpdateResponse: CreateOrderOrderUpdateResponse,
): string {
  return JSON.stringify(
    CreateOrderOrderUpdateResponse$outboundSchema.parse(
      createOrderOrderUpdateResponse,
    ),
  );
}

export function createOrderOrderUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrderOrderUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrderOrderUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrderOrderUpdateResponse' from JSON`,
  );
}
