/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authenticationLogin } from "../funcs/authenticationLogin.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Authentication extends ClientSDK {
  /**
   * Authenticate with the API by providing a username and password.
   */
  async login(
    security: operations.LoginSecurity,
    request: operations.LoginRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LoginResponse> {
    return unwrapAsync(authenticationLogin(
      this,
      security,
      request,
      options,
    ));
  }
}
