/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ingredientsGetIngredient } from "../funcs/ingredientsGetIngredient.js";
import { ingredientsListIngredients } from "../funcs/ingredientsListIngredients.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ingredients extends ClientSDK {
  /**
   * Get a list of ingredients.
   *
   * @remarks
   * Get a list of ingredients, if authenticated this will include stock levels and product codes otherwise it will only include public information.
   */
  async listIngredients(
    ingredients?: Array<string> | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListIngredientsResponse> {
    return unwrapAsync(ingredientsListIngredients(
      this,
      ingredients,
      options,
    ));
  }

  /**
   * Get an ingredient.
   *
   * @remarks
   * Get an ingredient by name, if authenticated this will include stock levels and product codes otherwise it will only include public information.
   */
  async getIngredient(
    name: string,
    options?: RequestOptions,
  ): Promise<operations.GetIngredientResponse> {
    return unwrapAsync(ingredientsGetIngredient(
      this,
      name,
      options,
    ));
  }
}
