workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/nolan-sdks/nolan-sdks/openapi
targets:
    my-first-target:
        target: typescript
        source: openapi
