/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateOrderRequest = {
  /**
   * The url to call when the order is updated.
   */
  callbackUrl?: string | undefined;
  order: components.OrderInput;
};

export type CreateOrderResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * The order was created successfully.
   */
  order?: components.Order | undefined;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const CreateOrderRequest$inboundSchema: z.ZodType<
  CreateOrderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  callback_url: z.string().optional(),
  Order: components.OrderInput$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "callback_url": "callbackUrl",
    "Order": "order",
  });
});

/** @internal */
export type CreateOrderRequest$Outbound = {
  callback_url?: string | undefined;
  Order: components.OrderInput$Outbound;
};

/** @internal */
export const CreateOrderRequest$outboundSchema: z.ZodType<
  CreateOrderRequest$Outbound,
  z.ZodTypeDef,
  CreateOrderRequest
> = z.object({
  callbackUrl: z.string().optional(),
  order: components.OrderInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    callbackUrl: "callback_url",
    order: "Order",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrderRequest$ {
  /** @deprecated use `CreateOrderRequest$inboundSchema` instead. */
  export const inboundSchema = CreateOrderRequest$inboundSchema;
  /** @deprecated use `CreateOrderRequest$outboundSchema` instead. */
  export const outboundSchema = CreateOrderRequest$outboundSchema;
  /** @deprecated use `CreateOrderRequest$Outbound` instead. */
  export type Outbound = CreateOrderRequest$Outbound;
}

export function createOrderRequestToJSON(
  createOrderRequest: CreateOrderRequest,
): string {
  return JSON.stringify(
    CreateOrderRequest$outboundSchema.parse(createOrderRequest),
  );
}

export function createOrderRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrderRequest' from JSON`,
  );
}

/** @internal */
export const CreateOrderResponse$inboundSchema: z.ZodType<
  CreateOrderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Order: components.Order$inboundSchema.optional(),
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Order": "order",
    "Error": "error",
  });
});

/** @internal */
export type CreateOrderResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Order?: components.Order$Outbound | undefined;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const CreateOrderResponse$outboundSchema: z.ZodType<
  CreateOrderResponse$Outbound,
  z.ZodTypeDef,
  CreateOrderResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  order: components.Order$outboundSchema.optional(),
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    order: "Order",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateOrderResponse$ {
  /** @deprecated use `CreateOrderResponse$inboundSchema` instead. */
  export const inboundSchema = CreateOrderResponse$inboundSchema;
  /** @deprecated use `CreateOrderResponse$outboundSchema` instead. */
  export const outboundSchema = CreateOrderResponse$outboundSchema;
  /** @deprecated use `CreateOrderResponse$Outbound` instead. */
  export type Outbound = CreateOrderResponse$Outbound;
}

export function createOrderResponseToJSON(
  createOrderResponse: CreateOrderResponse,
): string {
  return JSON.stringify(
    CreateOrderResponse$outboundSchema.parse(createOrderResponse),
  );
}

export function createOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrderResponse' from JSON`,
  );
}
