/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDrinkRequest = {
  name: string;
};

export type GetDrinkResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * A drink.
   */
  drink?: components.Drink | undefined;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const GetDrinkRequest$inboundSchema: z.ZodType<
  GetDrinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type GetDrinkRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetDrinkRequest$outboundSchema: z.ZodType<
  GetDrinkRequest$Outbound,
  z.ZodTypeDef,
  GetDrinkRequest
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDrinkRequest$ {
  /** @deprecated use `GetDrinkRequest$inboundSchema` instead. */
  export const inboundSchema = GetDrinkRequest$inboundSchema;
  /** @deprecated use `GetDrinkRequest$outboundSchema` instead. */
  export const outboundSchema = GetDrinkRequest$outboundSchema;
  /** @deprecated use `GetDrinkRequest$Outbound` instead. */
  export type Outbound = GetDrinkRequest$Outbound;
}

export function getDrinkRequestToJSON(
  getDrinkRequest: GetDrinkRequest,
): string {
  return JSON.stringify(GetDrinkRequest$outboundSchema.parse(getDrinkRequest));
}

export function getDrinkRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetDrinkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDrinkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDrinkRequest' from JSON`,
  );
}

/** @internal */
export const GetDrinkResponse$inboundSchema: z.ZodType<
  GetDrinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Drink: components.Drink$inboundSchema.optional(),
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Drink": "drink",
    "Error": "error",
  });
});

/** @internal */
export type GetDrinkResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Drink?: components.Drink$Outbound | undefined;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const GetDrinkResponse$outboundSchema: z.ZodType<
  GetDrinkResponse$Outbound,
  z.ZodTypeDef,
  GetDrinkResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  drink: components.Drink$outboundSchema.optional(),
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    drink: "Drink",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDrinkResponse$ {
  /** @deprecated use `GetDrinkResponse$inboundSchema` instead. */
  export const inboundSchema = GetDrinkResponse$inboundSchema;
  /** @deprecated use `GetDrinkResponse$outboundSchema` instead. */
  export const outboundSchema = GetDrinkResponse$outboundSchema;
  /** @deprecated use `GetDrinkResponse$Outbound` instead. */
  export type Outbound = GetDrinkResponse$Outbound;
}

export function getDrinkResponseToJSON(
  getDrinkResponse: GetDrinkResponse,
): string {
  return JSON.stringify(
    GetDrinkResponse$outboundSchema.parse(getDrinkResponse),
  );
}

export function getDrinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDrinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDrinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDrinkResponse' from JSON`,
  );
}
