/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetIngredientRequest = {
  name: string;
};

export type GetIngredientResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * An ingredient.
   */
  ingredient?: components.Ingredient | undefined;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const GetIngredientRequest$inboundSchema: z.ZodType<
  GetIngredientRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type GetIngredientRequest$Outbound = {
  name: string;
};

/** @internal */
export const GetIngredientRequest$outboundSchema: z.ZodType<
  GetIngredientRequest$Outbound,
  z.ZodTypeDef,
  GetIngredientRequest
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIngredientRequest$ {
  /** @deprecated use `GetIngredientRequest$inboundSchema` instead. */
  export const inboundSchema = GetIngredientRequest$inboundSchema;
  /** @deprecated use `GetIngredientRequest$outboundSchema` instead. */
  export const outboundSchema = GetIngredientRequest$outboundSchema;
  /** @deprecated use `GetIngredientRequest$Outbound` instead. */
  export type Outbound = GetIngredientRequest$Outbound;
}

export function getIngredientRequestToJSON(
  getIngredientRequest: GetIngredientRequest,
): string {
  return JSON.stringify(
    GetIngredientRequest$outboundSchema.parse(getIngredientRequest),
  );
}

export function getIngredientRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetIngredientRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIngredientRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIngredientRequest' from JSON`,
  );
}

/** @internal */
export const GetIngredientResponse$inboundSchema: z.ZodType<
  GetIngredientResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Ingredient: components.Ingredient$inboundSchema.optional(),
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Ingredient": "ingredient",
    "Error": "error",
  });
});

/** @internal */
export type GetIngredientResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Ingredient?: components.Ingredient$Outbound | undefined;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const GetIngredientResponse$outboundSchema: z.ZodType<
  GetIngredientResponse$Outbound,
  z.ZodTypeDef,
  GetIngredientResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  ingredient: components.Ingredient$outboundSchema.optional(),
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    ingredient: "Ingredient",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetIngredientResponse$ {
  /** @deprecated use `GetIngredientResponse$inboundSchema` instead. */
  export const inboundSchema = GetIngredientResponse$inboundSchema;
  /** @deprecated use `GetIngredientResponse$outboundSchema` instead. */
  export const outboundSchema = GetIngredientResponse$outboundSchema;
  /** @deprecated use `GetIngredientResponse$Outbound` instead. */
  export type Outbound = GetIngredientResponse$Outbound;
}

export function getIngredientResponseToJSON(
  getIngredientResponse: GetIngredientResponse,
): string {
  return JSON.stringify(
    GetIngredientResponse$outboundSchema.parse(getIngredientResponse),
  );
}

export function getIngredientResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetIngredientResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetIngredientResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetIngredientResponse' from JSON`,
  );
}
