/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListDrinksServerList = [
  "https://speakeasy.bar",
  "https://test.speakeasy.bar",
] as const;

export type ListDrinksSecurity = {
  bearerAuth?: string | undefined;
};

export type ListDrinksRequest = {
  /**
   * The type of drink to filter by. If not provided all drinks will be returned.
   */
  drinkType?: components.DrinkType | undefined;
};

export type ListDrinksResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * A list of drinks.
   */
  drinks?: Array<components.Drink> | undefined;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const ListDrinksSecurity$inboundSchema: z.ZodType<
  ListDrinksSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  bearerAuth: z.string().optional(),
});

/** @internal */
export type ListDrinksSecurity$Outbound = {
  bearerAuth?: string | undefined;
};

/** @internal */
export const ListDrinksSecurity$outboundSchema: z.ZodType<
  ListDrinksSecurity$Outbound,
  z.ZodTypeDef,
  ListDrinksSecurity
> = z.object({
  bearerAuth: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListDrinksSecurity$ {
  /** @deprecated use `ListDrinksSecurity$inboundSchema` instead. */
  export const inboundSchema = ListDrinksSecurity$inboundSchema;
  /** @deprecated use `ListDrinksSecurity$outboundSchema` instead. */
  export const outboundSchema = ListDrinksSecurity$outboundSchema;
  /** @deprecated use `ListDrinksSecurity$Outbound` instead. */
  export type Outbound = ListDrinksSecurity$Outbound;
}

export function listDrinksSecurityToJSON(
  listDrinksSecurity: ListDrinksSecurity,
): string {
  return JSON.stringify(
    ListDrinksSecurity$outboundSchema.parse(listDrinksSecurity),
  );
}

export function listDrinksSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ListDrinksSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDrinksSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDrinksSecurity' from JSON`,
  );
}

/** @internal */
export const ListDrinksRequest$inboundSchema: z.ZodType<
  ListDrinksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  drinkType: components.DrinkType$inboundSchema.optional(),
});

/** @internal */
export type ListDrinksRequest$Outbound = {
  drinkType?: string | undefined;
};

/** @internal */
export const ListDrinksRequest$outboundSchema: z.ZodType<
  ListDrinksRequest$Outbound,
  z.ZodTypeDef,
  ListDrinksRequest
> = z.object({
  drinkType: components.DrinkType$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListDrinksRequest$ {
  /** @deprecated use `ListDrinksRequest$inboundSchema` instead. */
  export const inboundSchema = ListDrinksRequest$inboundSchema;
  /** @deprecated use `ListDrinksRequest$outboundSchema` instead. */
  export const outboundSchema = ListDrinksRequest$outboundSchema;
  /** @deprecated use `ListDrinksRequest$Outbound` instead. */
  export type Outbound = ListDrinksRequest$Outbound;
}

export function listDrinksRequestToJSON(
  listDrinksRequest: ListDrinksRequest,
): string {
  return JSON.stringify(
    ListDrinksRequest$outboundSchema.parse(listDrinksRequest),
  );
}

export function listDrinksRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListDrinksRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDrinksRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDrinksRequest' from JSON`,
  );
}

/** @internal */
export const ListDrinksResponse$inboundSchema: z.ZodType<
  ListDrinksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Drinks: z.array(components.Drink$inboundSchema).optional(),
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Drinks": "drinks",
    "Error": "error",
  });
});

/** @internal */
export type ListDrinksResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Drinks?: Array<components.Drink$Outbound> | undefined;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const ListDrinksResponse$outboundSchema: z.ZodType<
  ListDrinksResponse$Outbound,
  z.ZodTypeDef,
  ListDrinksResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  drinks: z.array(components.Drink$outboundSchema).optional(),
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    drinks: "Drinks",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListDrinksResponse$ {
  /** @deprecated use `ListDrinksResponse$inboundSchema` instead. */
  export const inboundSchema = ListDrinksResponse$inboundSchema;
  /** @deprecated use `ListDrinksResponse$outboundSchema` instead. */
  export const outboundSchema = ListDrinksResponse$outboundSchema;
  /** @deprecated use `ListDrinksResponse$Outbound` instead. */
  export type Outbound = ListDrinksResponse$Outbound;
}

export function listDrinksResponseToJSON(
  listDrinksResponse: ListDrinksResponse,
): string {
  return JSON.stringify(
    ListDrinksResponse$outboundSchema.parse(listDrinksResponse),
  );
}

export function listDrinksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDrinksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDrinksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDrinksResponse' from JSON`,
  );
}
