/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListIngredientsRequest = {
  /**
   * A list of ingredients to filter by. If not provided all ingredients will be returned.
   */
  ingredients?: Array<string> | undefined;
};

export type ListIngredientsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * A list of ingredients.
   */
  ingredients?: Array<components.Ingredient> | undefined;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const ListIngredientsRequest$inboundSchema: z.ZodType<
  ListIngredientsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ingredients: z.array(z.string()).optional(),
});

/** @internal */
export type ListIngredientsRequest$Outbound = {
  ingredients?: Array<string> | undefined;
};

/** @internal */
export const ListIngredientsRequest$outboundSchema: z.ZodType<
  ListIngredientsRequest$Outbound,
  z.ZodTypeDef,
  ListIngredientsRequest
> = z.object({
  ingredients: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIngredientsRequest$ {
  /** @deprecated use `ListIngredientsRequest$inboundSchema` instead. */
  export const inboundSchema = ListIngredientsRequest$inboundSchema;
  /** @deprecated use `ListIngredientsRequest$outboundSchema` instead. */
  export const outboundSchema = ListIngredientsRequest$outboundSchema;
  /** @deprecated use `ListIngredientsRequest$Outbound` instead. */
  export type Outbound = ListIngredientsRequest$Outbound;
}

export function listIngredientsRequestToJSON(
  listIngredientsRequest: ListIngredientsRequest,
): string {
  return JSON.stringify(
    ListIngredientsRequest$outboundSchema.parse(listIngredientsRequest),
  );
}

export function listIngredientsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListIngredientsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListIngredientsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIngredientsRequest' from JSON`,
  );
}

/** @internal */
export const ListIngredientsResponse$inboundSchema: z.ZodType<
  ListIngredientsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Ingredients: z.array(components.Ingredient$inboundSchema).optional(),
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Ingredients": "ingredients",
    "Error": "error",
  });
});

/** @internal */
export type ListIngredientsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Ingredients?: Array<components.Ingredient$Outbound> | undefined;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const ListIngredientsResponse$outboundSchema: z.ZodType<
  ListIngredientsResponse$Outbound,
  z.ZodTypeDef,
  ListIngredientsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  ingredients: z.array(components.Ingredient$outboundSchema).optional(),
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    ingredients: "Ingredients",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListIngredientsResponse$ {
  /** @deprecated use `ListIngredientsResponse$inboundSchema` instead. */
  export const inboundSchema = ListIngredientsResponse$inboundSchema;
  /** @deprecated use `ListIngredientsResponse$outboundSchema` instead. */
  export const outboundSchema = ListIngredientsResponse$outboundSchema;
  /** @deprecated use `ListIngredientsResponse$Outbound` instead. */
  export type Outbound = ListIngredientsResponse$Outbound;
}

export function listIngredientsResponseToJSON(
  listIngredientsResponse: ListIngredientsResponse,
): string {
  return JSON.stringify(
    ListIngredientsResponse$outboundSchema.parse(listIngredientsResponse),
  );
}

export function listIngredientsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListIngredientsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListIngredientsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListIngredientsResponse' from JSON`,
  );
}
