/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LoginSecurity = {
  username: string;
  password: string;
};

export enum Type {
  ApiKey = "apiKey",
  Jwt = "JWT",
}

export type LoginRequestBody = {
  type: Type;
};

/**
 * The api key to use for authenticated endpoints.
 */
export type LoginResponseBody = {
  token?: string | undefined;
};

export type LoginResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * The api key to use for authenticated endpoints.
   */
  object?: LoginResponseBody | undefined;
  /**
   * An unknown error occurred interacting with the API.
   */
  error?: components.ErrorT | undefined;
};

/** @internal */
export const LoginSecurity$inboundSchema: z.ZodType<
  LoginSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  username: z.string(),
  password: z.string(),
});

/** @internal */
export type LoginSecurity$Outbound = {
  username: string;
  password: string;
};

/** @internal */
export const LoginSecurity$outboundSchema: z.ZodType<
  LoginSecurity$Outbound,
  z.ZodTypeDef,
  LoginSecurity
> = z.object({
  username: z.string(),
  password: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginSecurity$ {
  /** @deprecated use `LoginSecurity$inboundSchema` instead. */
  export const inboundSchema = LoginSecurity$inboundSchema;
  /** @deprecated use `LoginSecurity$outboundSchema` instead. */
  export const outboundSchema = LoginSecurity$outboundSchema;
  /** @deprecated use `LoginSecurity$Outbound` instead. */
  export type Outbound = LoginSecurity$Outbound;
}

export function loginSecurityToJSON(loginSecurity: LoginSecurity): string {
  return JSON.stringify(LoginSecurity$outboundSchema.parse(loginSecurity));
}

export function loginSecurityFromJSON(
  jsonString: string,
): SafeParseResult<LoginSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginSecurity' from JSON`,
  );
}

/** @internal */
export const Type$inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> =
  Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Type$ {
  /** @deprecated use `Type$inboundSchema` instead. */
  export const inboundSchema = Type$inboundSchema;
  /** @deprecated use `Type$outboundSchema` instead. */
  export const outboundSchema = Type$outboundSchema;
}

/** @internal */
export const LoginRequestBody$inboundSchema: z.ZodType<
  LoginRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: Type$inboundSchema,
});

/** @internal */
export type LoginRequestBody$Outbound = {
  type: string;
};

/** @internal */
export const LoginRequestBody$outboundSchema: z.ZodType<
  LoginRequestBody$Outbound,
  z.ZodTypeDef,
  LoginRequestBody
> = z.object({
  type: Type$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginRequestBody$ {
  /** @deprecated use `LoginRequestBody$inboundSchema` instead. */
  export const inboundSchema = LoginRequestBody$inboundSchema;
  /** @deprecated use `LoginRequestBody$outboundSchema` instead. */
  export const outboundSchema = LoginRequestBody$outboundSchema;
  /** @deprecated use `LoginRequestBody$Outbound` instead. */
  export type Outbound = LoginRequestBody$Outbound;
}

export function loginRequestBodyToJSON(
  loginRequestBody: LoginRequestBody,
): string {
  return JSON.stringify(
    LoginRequestBody$outboundSchema.parse(loginRequestBody),
  );
}

export function loginRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<LoginRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginRequestBody' from JSON`,
  );
}

/** @internal */
export const LoginResponseBody$inboundSchema: z.ZodType<
  LoginResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: z.string().optional(),
});

/** @internal */
export type LoginResponseBody$Outbound = {
  token?: string | undefined;
};

/** @internal */
export const LoginResponseBody$outboundSchema: z.ZodType<
  LoginResponseBody$Outbound,
  z.ZodTypeDef,
  LoginResponseBody
> = z.object({
  token: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginResponseBody$ {
  /** @deprecated use `LoginResponseBody$inboundSchema` instead. */
  export const inboundSchema = LoginResponseBody$inboundSchema;
  /** @deprecated use `LoginResponseBody$outboundSchema` instead. */
  export const outboundSchema = LoginResponseBody$outboundSchema;
  /** @deprecated use `LoginResponseBody$Outbound` instead. */
  export type Outbound = LoginResponseBody$Outbound;
}

export function loginResponseBodyToJSON(
  loginResponseBody: LoginResponseBody,
): string {
  return JSON.stringify(
    LoginResponseBody$outboundSchema.parse(loginResponseBody),
  );
}

export function loginResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<LoginResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginResponseBody' from JSON`,
  );
}

/** @internal */
export const LoginResponse$inboundSchema: z.ZodType<
  LoginResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  object: z.lazy(() => LoginResponseBody$inboundSchema).optional(),
  Error: components.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Error": "error",
  });
});

/** @internal */
export type LoginResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  object?: LoginResponseBody$Outbound | undefined;
  Error?: components.ErrorT$Outbound | undefined;
};

/** @internal */
export const LoginResponse$outboundSchema: z.ZodType<
  LoginResponse$Outbound,
  z.ZodTypeDef,
  LoginResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  object: z.lazy(() => LoginResponseBody$outboundSchema).optional(),
  error: components.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LoginResponse$ {
  /** @deprecated use `LoginResponse$inboundSchema` instead. */
  export const inboundSchema = LoginResponse$inboundSchema;
  /** @deprecated use `LoginResponse$outboundSchema` instead. */
  export const outboundSchema = LoginResponse$outboundSchema;
  /** @deprecated use `LoginResponse$Outbound` instead. */
  export type Outbound = LoginResponse$Outbound;
}

export function loginResponseToJSON(loginResponse: LoginResponse): string {
  return JSON.stringify(LoginResponse$outboundSchema.parse(loginResponse));
}

export function loginResponseFromJSON(
  jsonString: string,
): SafeParseResult<LoginResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LoginResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LoginResponse' from JSON`,
  );
}
