/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { IngredientType, IngredientType$ } from "./ingredienttype";
import * as z from "zod";

export type IngredientInput = {
    /**
     * The name of the ingredient.
     */
    name: string;
    /**
     * The type of ingredient.
     */
    type: IngredientType;
    /**
     * The product code of the ingredient, only available when authenticated.
     */
    productCode?: string | undefined;
};

/** @internal */
export namespace IngredientInput$ {
    export const inboundSchema: z.ZodType<IngredientInput, z.ZodTypeDef, unknown> = z
        .object({
            name: z.string(),
            type: IngredientType$.inboundSchema,
            productCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                name: v.name,
                type: v.type,
                ...(v.productCode === undefined ? null : { productCode: v.productCode }),
            };
        });

    export type Outbound = {
        name: string;
        type: string;
        productCode?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, IngredientInput> = z
        .object({
            name: z.string(),
            type: IngredientType$.outboundSchema,
            productCode: z.string().optional(),
        })
        .transform((v) => {
            return {
                name: v.name,
                type: v.type,
                ...(v.productCode === undefined ? null : { productCode: v.productCode }),
            };
        });
}
