/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  IngredientType,
  IngredientType$inboundSchema,
  IngredientType$outboundSchema,
} from "./ingredienttype.js";

export type Ingredient = {
  /**
   * The name of the ingredient.
   */
  name: string;
  /**
   * The type of ingredient.
   */
  type: IngredientType;
  /**
   * The number of units of the ingredient in stock, only available when authenticated.
   */
  stock?: number | undefined;
  /**
   * The product code of the ingredient, only available when authenticated.
   */
  productCode?: string | undefined;
};

/** @internal */
export const Ingredient$inboundSchema: z.ZodType<
  Ingredient,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  type: IngredientType$inboundSchema,
  stock: z.number().int().optional(),
  productCode: z.string().optional(),
});

/** @internal */
export type Ingredient$Outbound = {
  name: string;
  type: string;
  stock?: number | undefined;
  productCode?: string | undefined;
};

/** @internal */
export const Ingredient$outboundSchema: z.ZodType<
  Ingredient$Outbound,
  z.ZodTypeDef,
  Ingredient
> = z.object({
  name: z.string(),
  type: IngredientType$outboundSchema,
  stock: z.number().int().optional(),
  productCode: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Ingredient$ {
  /** @deprecated use `Ingredient$inboundSchema` instead. */
  export const inboundSchema = Ingredient$inboundSchema;
  /** @deprecated use `Ingredient$outboundSchema` instead. */
  export const outboundSchema = Ingredient$outboundSchema;
  /** @deprecated use `Ingredient$Outbound` instead. */
  export type Outbound = Ingredient$Outbound;
}

export function ingredientToJSON(ingredient: Ingredient): string {
  return JSON.stringify(Ingredient$outboundSchema.parse(ingredient));
}

export function ingredientFromJSON(
  jsonString: string,
): SafeParseResult<Ingredient, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ingredient$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ingredient' from JSON`,
  );
}
