/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { IngredientType, IngredientType$ } from "./ingredienttype";
import * as z from "zod";

export type Ingredient = {
    /**
     * The name of the ingredient.
     */
    name: string;
    /**
     * The type of ingredient.
     */
    type: IngredientType;
    /**
     * The number of units of the ingredient in stock, only available when authenticated.
     */
    stock?: number | undefined;
    /**
     * The product code of the ingredient, only available when authenticated.
     */
    productCode?: string | undefined;
};

/** @internal */
export namespace Ingredient$ {
    export const inboundSchema: z.ZodType<Ingredient, z.ZodTypeDef, unknown> = z.object({
        name: z.string(),
        type: IngredientType$.inboundSchema,
        stock: z.number().int().optional(),
        productCode: z.string().optional(),
    });

    export type Outbound = {
        name: string;
        type: string;
        stock?: number | undefined;
        productCode?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Ingredient> = z.object({
        name: z.string(),
        type: IngredientType$.outboundSchema,
        stock: z.number().int().optional(),
        productCode: z.string().optional(),
    });
}
