/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { OrderType, OrderType$ } from "./ordertype";
import * as z from "zod";

/**
 * An order for a drink or ingredient.
 */
export type OrderInput = {
    /**
     * The type of order.
     */
    type: OrderType;
    /**
     * The product code of the drink or ingredient.
     */
    productCode: string;
    /**
     * The number of units of the drink or ingredient to order.
     */
    quantity: number;
};

/** @internal */
export namespace OrderInput$ {
    export const inboundSchema: z.ZodType<OrderInput, z.ZodTypeDef, unknown> = z
        .object({
            type: OrderType$.inboundSchema,
            productCode: z.string(),
            quantity: z.number().int(),
        })
        .transform((v) => {
            return {
                type: v.type,
                productCode: v.productCode,
                quantity: v.quantity,
            };
        });

    export type Outbound = {
        type: string;
        productCode: string;
        quantity: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, OrderInput> = z
        .object({
            type: OrderType$.outboundSchema,
            productCode: z.string(),
            quantity: z.number().int(),
        })
        .transform((v) => {
            return {
                type: v.type,
                productCode: v.productCode,
                quantity: v.quantity,
            };
        });
}
