/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    apiKey?: string | undefined;
    bearerAuth?: string | undefined;
};

/** @internal */
export namespace Security$ {
    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
        .object({
            apiKey: z.string().optional(),
            bearerAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.apiKey === undefined ? null : { apiKey: v.apiKey }),
                ...(v.bearerAuth === undefined ? null : { bearerAuth: v.bearerAuth }),
            };
        });

    export type Outbound = {
        apiKey?: string | undefined;
        bearerAuth?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            apiKey: z.string().optional(),
            bearerAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.apiKey === undefined ? null : { apiKey: v.apiKey }),
                ...(v.bearerAuth === undefined ? null : { bearerAuth: v.bearerAuth }),
            };
        });
}
